### PR TITLE
Migration to multiformats - WIP

### PR DESCRIPTION
**Pull request by msporny**
This is an attempt to migrate cryptonyms to multiformats.

### CODE REVIEW

**Comment by mattcollier** [comment]
@msporny @dlongley I see that the `update-terminology` has been included in this PR, can we safely delete that branch now?

This branch needs to be rebased on master after a dependency update there.  I'm happy to do that rebasing, but want to make sure @msporny is aware.

**Comment by dlongley** [comment]
cc: @dmitrizagidulin -- what's the status here?

**Comment by mattcollier** [comment]
This branch has been rebased on master.

**Comment by msporny** [comment]
> @msporny @dlongley I see that the update-terminology has been included in this PR, can we safely delete that branch now?

Yes, I think so, as long as no one else is depending on that branch (I'd check veres-one-* and bedrock-ledger* branches). I'm guessing some of the stuff that @dmitrizagidulin is working on might be affected?

> This branch needs to be rebased on master after a dependency update there. I'm happy to do that rebasing, but want to make sure @msporny is aware.

Rebase away.

**Comment by dmitrizagidulin** [comment]
Go ahead and rebase, I'm not using this lib directly.

**Pull request merged**
